 
###
GET http://localhost:3000/tasks?status=IN_PROGRESS HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/tasks/8126f850-e1f6-11e9-a560-e9cf3ef03efs6 HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "",
    "description": "someDescription"
}


###
PUT http://localhost:3000/tasks/ HTTP/1.1
content-type: application/json

{
    "name": "some name",
    "isComplete": true
}


###
DELETE http://localhost:3000/tasks/90faab40-e1e8-11e9-b90f-7b2db1333ff4 HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3000/tasks/8126f850-e1f6-11e9-a560-e9cf3ef03ef6/status HTTP/1.1
content-type: application/json

{
    "status": "IN_PROGRESS"
}