 
###
GET http://localhost:3000/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsbGEiLCJpYXQiOjE1Njk3NzQzMjksImV4cCI6MTU2OTc3NzkyOX0.EM7nh60gom8mYahg9uEajgbPaYP067VSFRkUNFgPSx0


###
GET http://localhost:3000/tasks/ HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsbGEiLCJpYXQiOjE1Njk3NzQzMjksImV4cCI6MTU2OTc3NzkyOX0.EM7nh60gom8mYahg9uEajgbPaYP067VSFRkUNFgPSx0


{
    "title": "title 2",
    "description": "someDescription"
}


###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "Dima",
    "password": "Aa123___"
}


###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "Alla",
    "password": "Aa123___"
}


###
PUT http://localhost:3000/tasks/ HTTP/1.1
content-type: application/json

{
    "name": "some name",
    "isComplete": true
}


###
DELETE http://localhost:3000/tasks/1 HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3000/tasks/1/status HTTP/1.1
content-type: application/json

{
    "status": "IN_PROGRESS"
}