 
###
GET http://localhost:3000/tasks HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/tasks/ HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "",
    "description": "someDescription"
}


###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "Alla",
    "password": "Aa123___"
}


###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "Alla",
    "password": "Aa123___"
}


###
PUT http://localhost:3000/tasks/ HTTP/1.1
content-type: application/json

{
    "name": "some name",
    "isComplete": true
}


###
DELETE http://localhost:3000/tasks/1 HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3000/tasks/1/status HTTP/1.1
content-type: application/json

{
    "status": "IN_PROGRESS"
}